[book]
authors = ["Robert"]
language = "en"
multilingual = false
src = "src"
title = "The Promise of Wasm outside of the Web"

[output.html]
additional-css = ["src/assets/main.css"]

[build]
build-dir = "docs"

[preprocessor.presentation-preprocessor]